// <auto-generated/>
/*
* C# / XNA  port of Bullet (c) 2011 Mark Neale <xexuxjy@hotmail.com>
*
* Bullet Continuous Collision Detection and Physics Library
* Copyright (c) 2003-2008 Erwin Coumans  http://www.bulletphysics.com/
*
* This software is provided 'as-is', without any express or implied warranty.
* In no event will the authors be held liable for any damages arising from
* the use of this software.
* 
* Permission is granted to anyone to use this software for any purpose, 
* including commercial applications, and to alter it and redistribute it
* freely, subject to the following restrictions:
* 
* 1. The origin of this software must not be misrepresented; you must not
*    claim that you wrote the original software. If you use this software
*    in a product, an acknowledgment in the product documentation would be
*    appreciated but is not required.
* 2. Altered source versions must be plainly marked as such, and must not be
*    misrepresented as being the original software.
* 3. This notice may not be removed or altered from any source distribution.
*/

using Evergine.Mathematics;
using System.Runtime.InteropServices;

namespace BulletSharp
{
	[StructLayoutAttribute(LayoutKind.Explicit, CharSet = CharSet.Ansi)]
	public struct DefaultColors
    {
		[FieldOffset(0)]
		public Vector3 ActiveObject;

		[FieldOffset(16)]
		public Vector3 DeactivatedObject;

		[FieldOffset(32)]
		public Vector3 WantsDeactivationObject;

		[FieldOffset(48)]
		public Vector3 DisabledDeactivationObject;

		[FieldOffset(64)]
		public Vector3 DisabledSimulationObject;

		[FieldOffset(80)]
		public Vector3 Aabb;

		[FieldOffset(96)]
		public Vector3 ContactPoint;

		public static DefaultColors Default
        {
			get
            {
				return new DefaultColors()
				{
					ActiveObject = new Vector3(1, 1, 1),
					DeactivatedObject = new Vector3(0, 1, 0),
					WantsDeactivationObject = new Vector3(0, 1, 1),
					DisabledDeactivationObject = new Vector3(1, 0, 0),
					DisabledSimulationObject = new Vector3(1, 1, 0),
					Aabb = new Vector3(1, 0, 0),
					ContactPoint = new Vector3(1, 1, 0)
				};
            }
        }
	}
}