// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Security;
using Evergine.Mathematics;
using static BulletSharp.EvergineUnsafeNativeMethods;


namespace BulletSharp
{
    public static class EvergineBulletHelpers
    {
        public static CollisionObject GetCollisionObjectFromPtr(IntPtr obj)
        {
            return CollisionObject.GetManaged(obj);
        }

    }
}
