// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Security;
using Evergine.Mathematics;
using static BulletSharp.EvergineUnsafeNativeMethods;


namespace BulletSharp
{
    public abstract partial class DebugDraw : BulletDisposableObject
    {
        protected DefaultColors DefaultColors
        {
            set
            {
                unsafe
                {
                    var debugDraw = value;
                    btIDebugDraw_setDefaultColors(this.Native, new IntPtr((void*)&debugDraw));
                }
            }
        }
    }
}
