// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Security;
using Evergine.Mathematics;
using static BulletSharp.EvergineUnsafeNativeMethods;


namespace BulletSharp
{
    public partial class ConvexHullShape : PolyhedralConvexAabbCachingShape
    {
        // Constructor used to pass vertexbuffer pointer, instead vertex arrays.
        public ConvexHullShape(IntPtr pointsPtr, int numPoints, int stride = 3 * sizeof(float))
        {
            IntPtr native = btConvexHullShape_new4(pointsPtr, numPoints, stride);
            InitializeCollisionShape(native);
        }
    }
}
